# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.18.6

# Mod Properties
mod_version=1.0.0
maven_group=froyln
archives_base_name=BotInventory-Carpet

# Dependencies
carpet_version=1.21.11-1.4.194+v260107
sgui_version=1.12.0+1.21.11
